name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  step_1:
    name: Build da Aplicação
    uses: ./.github/workflows/build.yml

  step_2:
    name: Testes Unitários
    needs: step_1
    uses: ./.github/workflows/test.yml

  step_3:
    name: Comentar PR
    permissions: write-all
    needs: step_2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Comentar PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Analise o PR com carinho ❤😁
          reactions: eyes, rocket
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      