name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  step_1:
    uses: ./.github/workflows/build.yml

  step_2:
    needs: step_1
    uses: ./.github/workflows/test.yml

  comment-pr:
    permissions: write-all
    needs: step_2
    runs-on: ubuntu-latest
    name: Comment PR
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Comentar PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Olá! Obrigado por abrir este PR. 
            O build e os testes foram executados com
            sucesso.
          reactions: eyes, rocket
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      